language: python
python:
  - "2.7"
#  - "3.3"
#  - "3.5"
  - "3.6"
# command to install dependencies
#install: "pip install -r requirements.txt"
# command to run tests
install:
 - pip install numpy xlrd xlwt openpyxl h5py
 - python setup.py install
script:
   # Run all the tests but those marked 'fortran' or 'pandas'
 - py.test
